package originalgremlin.from001to050;

import originalgremlin.Euler;

/**
 * Pentagon numbers
 * Problem 44
 *
 * Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:
 *
 * 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
 *
 * It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.
 *
 * Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is
 * minimised; what is the value of D?
 */

public class Problem44 {
    public static void main (String[] args) {
        int N = 2500;
        long min = Long.MAX_VALUE;
        long Pj, Pk, sum, diff;
        for (int j = 1; j <= N; j++) {
            Pj = Euler.getPentagonNumber(j);
            for (int k = j + 1; k <= N; k++) {
                Pk = Euler.getPentagonNumber(k);
                sum = Pj + Pk;
                diff = Pk - Pj;
                if (Euler.isPentagonNumber(sum) && Euler.isPentagonNumber(diff)) {
                    min = Math.min(diff, min);
                }
            }
        }
        System.out.println(min);
    }
}
