package originalgremlin.from001to050;

import originalgremlin.Euler;

import java.util.stream.IntStream;
import java.util.stream.LongStream;

/**
 * Triangular, pentagonal, and hexagonal
 * Problem 45
 *
 * Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
 *
 * Triangle	 	    Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
 * Pentagonal	 	Pn=n(3n−1)/2	1, 5, 12, 22, 35, ...
 * Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
 *
 * It can be verified that T285 = P165 = H143 = 40755.
 *
 * Find the next triangle number that is also pentagonal and hexagonal.
 */

public class Problem45 {
    public static void main (String[] args) {
        long num = LongStream.iterate(286, i -> i + 1)
                .map(Euler::getTriangleNumber)
                .filter(Euler::isPentagonNumber)
                .filter(Euler::isHexagonNumber)
                .findFirst().orElse(0);
        System.out.println(num);
    }
}
